/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_mainWindow (void);
GtkWidget* create_TREEVIEW (void);
GtkWidget* create_Authentication (void);
GtkWidget* create_AdminCitoyen (void);
GtkWidget* create_AfficherAgents (void);
GtkWidget* create_AjoutAgent (void);
GtkWidget* create_modifieragent (void);
GtkWidget* create_supprimeragent (void);
GtkWidget* create_Choix (void);
GtkWidget* create_windowParkingHome (void);
GtkWidget* create_windowParkingSup (void);
GtkWidget* create_windowParkingAjout (void);
GtkWidget* create_windowParkingModif (void);
GtkWidget* create_windowParkingAffectation (void);
GtkWidget* create_Citoyen (void);
GtkWidget* create_Facture (void);
