/*
 * Initial main.c file generated by Glade. Edit as required.
 * Glade will not overwrite this file.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <gtk/gtk.h>

#include "interface.h"
#include "support.h"

int
main (int argc, char *argv[])
{
  GtkWidget *mainWindow;
  GtkWidget *TREEVIEW;
  GtkWidget *Authentication;
  GtkWidget *AdminCitoyen;
  GtkWidget *windowParkingHome;
  GtkWidget *AfficherAgents;
  GtkWidget *AjoutAgent;
  GtkWidget *modifieragent;
  GtkWidget *supprimeragent;
  GtkWidget *Citoyen; 
  GtkWidget *Facture;
  
#ifdef ENABLE_NLS
  bindtextdomain (GETTEXT_PACKAGE, PACKAGE_LOCALE_DIR);
  bind_textdomain_codeset (GETTEXT_PACKAGE, "UTF-8");
  textdomain (GETTEXT_PACKAGE);
#endif

  gtk_set_locale ();
  gtk_init (&argc, &argv);

  add_pixmap_directory (PACKAGE_DATA_DIR "/" PACKAGE "/pixmaps");

  /*
   * The following code was added by Glade to create one of each component
   * (except popup menus), just so that you see something after building
   * the project. Delete any components that you don't want shown initially.
   */
  mainWindow = create_mainWindow ();
  Authentication = create_Authentication();
  TREEVIEW = create_TREEVIEW();
  AdminCitoyen = create_AdminCitoyen ();
  windowParkingHome = create_windowParkingHome ();
  AfficherAgents = create_AfficherAgents ();
  AjoutAgent = create_AjoutAgent ();
  modifieragent = create_modifieragent ();
  supprimeragent = create_supprimeragent ();
  Citoyen = create_Citoyen ();
  Facture = create_Facture ();
  
  gtk_widget_show (AdminCitoyen);
  

  gtk_main ();
  return 0;
}

